//
// Created by vetinari on 01.12.20.
//

#ifndef MASTER_PROJECT_C_PART_COOLCONST_H
#define MASTER_PROJECT_C_PART_COOLCONST_H

#define EPSILON 1e-6
#define AUTOMATIC_LOADING 1
#define MAX_FLIPS 100

#endif //MASTER_PROJECT_C_PART_COOLCONST_H
